//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTheatre.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class misc_cz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal misc_cz() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenTheatre.Languages.misc-cz", typeof(misc_cz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokončeno.
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Připojování.
        /// </summary>
        internal static string connecting {
            get {
                return ResourceManager.GetString("connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodařilo se připojit k serveru. Pokud problém přetrvá, založte issue na naší stránce na GitHubu..
        /// </summary>
        internal static string errorConnectToServer {
            get {
                return ResourceManager.GetString("errorConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodařilo se připojit k internetu. Pro používání OpenTheatre je vyžadován internet. Zkontrolujte připojení a zkuste to znovu..
        /// </summary>
        internal static string errorNoInternetConnection {
            get {
                return ResourceManager.GetString("errorNoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při hledání souborů, zkuste to znovu později....
        /// </summary>
        internal static string errorSearch {
            get {
                return ResourceManager.GetString("errorSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokální.
        /// </summary>
        internal static string local {
            get {
                return ResourceManager.GetString("local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaná složka pro stahování neexistuje. Vyberte jinou složku v nastavení..
        /// </summary>
        internal static string noDownloadDirectory {
            get {
                return ResourceManager.GetString("noDownloadDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro změnu jazyka je vyžadován restart programu. Chcete pokračovat?.
        /// </summary>
        internal static string restartRequiredLanguage {
            get {
                return ResourceManager.GetString("restartRequiredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programu.
        /// </summary>
        internal static string titleAbout {
            get {
                return ResourceManager.GetString("titleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záložky.
        /// </summary>
        internal static string titleBookmarks {
            get {
                return ResourceManager.GetString("titleBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stahování.
        /// </summary>
        internal static string titleDownloads {
            get {
                return ResourceManager.GetString("titleDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory.
        /// </summary>
        internal static string titleFiles {
            get {
                return ResourceManager.GetString("titleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filmy.
        /// </summary>
        internal static string titleMovies {
            get {
                return ResourceManager.GetString("titleMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je vyžadován restart.
        /// </summary>
        internal static string titleRestartRequired {
            get {
                return ResourceManager.GetString("titleRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        internal static string titleSettings {
            get {
                return ResourceManager.GetString("titleSettings", resourceCulture);
            }
        }
    }
}
