//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTheatre.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class misc_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal misc_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenTheatre.Languages.misc-es", typeof(misc_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completar.
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectando.
        /// </summary>
        internal static string connecting {
            get {
                return ResourceManager.GetString("connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al conectar con el servidor. Si el problema persiste, abra un problema en nuestra página de GitHub..
        /// </summary>
        internal static string errorConnectToServer {
            get {
                return ResourceManager.GetString("errorConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró conexión a Internet. Debe estar conectado a Internet para usar OpenTheatre. Por favor revise su conexión o intente de nuevo..
        /// </summary>
        internal static string errorNoInternetConnection {
            get {
                return ResourceManager.GetString("errorNoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar archivos, inténtalo de nuevo más tarde ....
        /// </summary>
        internal static string errorSearch {
            get {
                return ResourceManager.GetString("errorSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string local {
            get {
                return ResourceManager.GetString("local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El directorio de descargas especificado no existe. Seleccione la carpeta en su configuración..
        /// </summary>
        internal static string noDownloadDirectory {
            get {
                return ResourceManager.GetString("noDownloadDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tendrá que reiniciar para que los cambios de idioma surtan efecto. ¿Te gustaria continuar?.
        /// </summary>
        internal static string restartRequiredLanguage {
            get {
                return ResourceManager.GetString("restartRequiredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        internal static string titleAbout {
            get {
                return ResourceManager.GetString("titleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcadores.
        /// </summary>
        internal static string titleBookmarks {
            get {
                return ResourceManager.GetString("titleBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargas.
        /// </summary>
        internal static string titleDownloads {
            get {
                return ResourceManager.GetString("titleDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos.
        /// </summary>
        internal static string titleFiles {
            get {
                return ResourceManager.GetString("titleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Películas.
        /// </summary>
        internal static string titleMovies {
            get {
                return ResourceManager.GetString("titleMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinicio requerido.
        /// </summary>
        internal static string titleRestartRequired {
            get {
                return ResourceManager.GetString("titleRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraciones.
        /// </summary>
        internal static string titleSettings {
            get {
                return ResourceManager.GetString("titleSettings", resourceCulture);
            }
        }
    }
}
