//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opentheatre_app.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class misc_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal misc_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("opentheatre_app.Languages.misc-fr", typeof(misc_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achevée.
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De liaison.
        /// </summary>
        internal static string connecting {
            get {
                return ResourceManager.GetString("connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec de connexion au serveur. Si ce problème persiste, veuillez ouvrir un problème sur notre page GitHub..
        /// </summary>
        internal static string errorConnectToServer {
            get {
                return ResourceManager.GetString("errorConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune connexion Internet trouvée. Vous devez être connecté à Internet pour utiliser OpenTheatre. Veuillez vérifier votre connexion ou réessayer..
        /// </summary>
        internal static string errorNoInternetConnection {
            get {
                return ResourceManager.GetString("errorNoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la recherche de fichiers, réessayez plus tard ....
        /// </summary>
        internal static string errorSearch {
            get {
                return ResourceManager.GetString("errorSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string local {
            get {
                return ResourceManager.GetString("local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le répertoire de téléchargement spécifié n&apos;existe pas. Veuillez sélectionner le dossier dans vos paramètres..
        /// </summary>
        internal static string noDownloadDirectory {
            get {
                return ResourceManager.GetString("noDownloadDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devrez redémarrer pour que les modifications de langue prennent effet. Voulez-vous continuer?.
        /// </summary>
        internal static string restartRequiredLanguage {
            get {
                return ResourceManager.GetString("restartRequiredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redémarrage requis.
        /// </summary>
        internal static string titleRestartRequired {
            get {
                return ResourceManager.GetString("titleRestartRequired", resourceCulture);
            }
        }
    }
}
